documents:
- doc_id: '-7655343'
  title: Oʻzbekiston Respublikasining Suv kodeksi
  type: kodeks
- doc_id: '-6257288'
  title: Oʻzbekiston Respublikasining Mehnat kodeksi
  type: kodeks
- doc_id: '-5307951'
  title: Oʻzbekiston Respublikasining Shaharsozlik kodeksi
  type: kodeks
- doc_id: '-4674902'
  title: Oʻzbekiston Respublikasining Soliq kodeksi
  type: kodeks
- doc_id: '-4386848'
  title: Oʻzbekiston Respublikasining Saylov kodeksi
  type: kodeks
- doc_id: '-3527353'
  title: Oʻzbekiston Respublikasining Maʼmuriy sud ishlarini yuritish toʻgʻrisidagi
    kodeksi
  type: kodeks
- doc_id: '-3523891'
  title: Oʻzbekiston Respublikasining Iqtisodiy protsessual kodeksi
  type: kodeks
- doc_id: '-3517337'
  title: Oʻzbekiston Respublikasining Fuqarolik protsessual kodeksi
  type: kodeks
- doc_id: '-2876354'
  title: Oʻzbekiston Respublikasining Bojxona kodeksi
  type: kodeks
- doc_id: '-2304138'
  title: Oʻzbekiston Respublikasining Budjet kodeksi
  type: kodeks
- doc_id: '-106136'
  title: Oʻzbekiston Respublikasining Uy-joy kodeksi
  type: kodeks
- doc_id: '-104720'
  title: Oʻzbekiston Respublikasining Oila kodeksi
  type: kodeks
- doc_id: '-152653'
  title: Oʻzbekiston Respublikasining Yer kodeksi
  type: kodeks
- doc_id: '-163629'
  title: Oʻzbekiston Respublikasining Jinoyat-ijroiya kodeksi
  type: kodeks
- doc_id: '-180552'
  title: Oʻzbekiston Respublikasining Fuqarolik kodeksi (ikkinchi qism)
  type: kodeks
- doc_id: '-111189'
  title: Oʻzbekiston Respublikasining Fuqarolik kodeksi (birinchi qism)
  type: kodeks
- doc_id: '-111460'
  title: Oʻzbekiston Respublikasining Jinoyat-protsessual kodeksi
  type: kodeks
- doc_id: '-111453'
  title: Oʻzbekiston Respublikasining Jinoyat kodeksi
  type: kodeks
- doc_id: '-97664'
  title: Oʻzbekiston Respublikasining Maʼmuriy javobgarlik toʻgʻrisidagi kodeksi
  type: kodeks
- doc_id: '-55594'
  title: Oʻzbekiston Respublikasining Havo kodeksi
  type: kodeks
